#!/bin/bash

set -ouex pipefail

### Install packages

# Packages can be installed from any enabled yum repo on the image.
# RPMfusion repos are available by default in ublue main images
# List of rpmfusion packages can be found here:
# https://mirrors.rpmfusion.org/mirrorlist?path=free/fedora/updates/39/x86_64/repoview/index.html&protocol=https&redirect=1

# Use a COPR Example:
#
# dnf5 -y copr enable ublue-os/staging
# dnf5 -y install package
# Disable COPRs so they don't end up enabled on the final image:
# dnf5 -y copr disable ublue-os/staging

dnf5 -y install timg htop btop lm_sensors trash

dnf5 -y copr enable kylegospo/webapp-manager
dnf5 -y install webapp-manager
dnf5 -y copr disable kylegospo/webapp-manager
#
# dnf5 -y copr enable pgdev/ghostty
# dnf5 -y install ghostty
# dnf5 -y copr disable pgdev/ghostty

#install macbook ambient sensor
git clone https://github.com/harttle/macbook-lighter.git
cd macbook-lighter
install -Dm644 macbook-lighter.conf /etc/macbook-lighter.conf
install -Dm644 "macbook-lighter.service" "/usr/lib/systemd/system/macbook-lighter.service"
install -Dm755 "src/macbook-lighter-ambient.sh" "/usr/bin/macbook-lighter-ambient"
install -Dm755 "src/macbook-lighter-screen.sh" "/usr/bin/macbook-lighter-screen"
install -Dm755 "src/macbook-lighter-kbd.sh" "/usr/bin/macbook-lighter-kbd"
cd ..
rm -rf macbook-lighter
